// src/controllers/featuresController.js
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import asyncHandler from "express-async-handler";
import Vehicle from "../models/Vehicle.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// JSON generated by your CSV script, now moved into API repo
const detailsPath = path.join(
  __dirname,
  "..",
  "data",
  "features",
  "features_details.json",
);
const variantsPath = path.join(
  __dirname,
  "..",
  "data",
  "features",
  "features_variants.json",
);

let DETAILS = {};
let VARIANTS_BY_MODEL = {};
let ALL_VARIANTS_FLAT = [];

function loadFeatures() {
  try {
    DETAILS = JSON.parse(fs.readFileSync(detailsPath, "utf8"));
    VARIANTS_BY_MODEL = JSON.parse(fs.readFileSync(variantsPath, "utf8"));
    ALL_VARIANTS_FLAT = Object.values(VARIANTS_BY_MODEL).flat();
    console.log(
      `[features] loaded ${Object.keys(DETAILS).length} detail entries, ${ALL_VARIANTS_FLAT.length} variants`,
    );
  } catch (err) {
    console.error("Error loading features JSON:", err);
    DETAILS = {};
    VARIANTS_BY_MODEL = {};
    ALL_VARIANTS_FLAT = [];
  }
}

// load once on startup
loadFeatures();

// @desc  Get all raw feature details (id -> {features})
// @route GET /api/features/details
// @access Public
export const getFeatureDetails = asyncHandler(async (req, res) => {
  res.json(DETAILS);
});

// @desc  Get all feature variants (flattened)
// @route GET /api/features/variants
// @access Public
export const getFeatureVariants = asyncHandler(async (req, res) => {
  res.json(ALL_VARIANTS_FLAT);
});

// @desc  Get one variant's feature details
// @route GET /api/features/variant/:id
// @access Public
export const getFeatureVariantById = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const detail = DETAILS[id];
  if (!detail) {
    res.status(404);
    throw new Error("Variant features not found");
  }
  res.json(detail);
});

// helper to normalize feature value strings a bit
const normalizeValue = (val) => {
  if (!val && val !== 0) return "Not Available";
  const v = String(val).trim().toLowerCase();
  if (["yes", "y", "available", "present"].includes(v)) return "Yes";
  if (["no", "n", "not available", "na", "n/a"].includes(v))
    return "Not Available";
  return val;
};

// @desc  Get combined variants with pricing + features
// @route GET /api/features/variants-with-price
// @access Public
export const getVariantsWithPriceAndFeatures = asyncHandler(
  async (req, res) => {
    // optional query params later (city, fuel, etc.)
    const { city } = req.query;

    const vehicleQuery = {};
    if (city) vehicleQuery.city = city;

    const vehicles = await Vehicle.find(vehicleQuery).sort({
      make: 1,
      model: 1,
      variant: 1,
    });

    // index vehicles by make+model+variant for join
    const vehicleIndex = {};
    vehicles.forEach((v) => {
      const key = `${(v.make || "").trim().toLowerCase()}|${(v.model || "")
        .trim()
        .toLowerCase()}|${(v.variant || "").trim().toLowerCase()}`;
      if (!vehicleIndex[key]) vehicleIndex[key] = [];
      vehicleIndex[key].push(v);
    });

    const result = ALL_VARIANTS_FLAT.map((fv) => {
      const key = `${(fv.make || "").trim().toLowerCase()}|${(fv.model || "")
        .trim()
        .toLowerCase()}|${(fv.variant || "").trim().toLowerCase()}`;

      const candidates = vehicleIndex[key] || [];
      // naive: pick first; you can refine with fuel/city if needed
      const vehicle = candidates[0] || null;

      const detail = DETAILS[fv.id];

      return {
        id: fv.id,
        make: fv.make,
        model: fv.model,
        variant: fv.variant,
        fuel: fv.fuel,
        transmission: fv.transmission,
        tags: fv.tags || [],
        price: vehicle?.exShowroom ?? null,
        onRoadPrice: vehicle?.onRoadPrice ?? null,
        city: vehicle?.city ?? null,
        vehicleId: vehicle?._id ?? null,
        features: (detail?.features || []).map((f) => ({
          ...f,
          value: normalizeValue(f.value),
        })),
      };
    });

    res.json({ success: true, count: result.length, data: result });
  },
);
