import Booking from "../../models/Booking.js";
import Bank from "../../models/Bank.js";
import BankDirectory from "../../models/BankDirectory.js";
import Channel from "../../models/Channel.js";
import Customer from "../../models/Customer.js";
import DeliveryOrder from "../../models/DeliveryOrder.js";
import InsuranceCase from "../../models/InsuranceCase.js";
import Loan from "../../models/Loan.js";
import Payment from "../../models/Payment.js";
import Quotation from "../../models/Quotation.js";
import Receivable from "../../models/Receivable.js";
import Showroom from "../../models/Showroom.js";
import UsedCarLead from "../../models/UsedCarLead.js";
import Vehicle from "../../models/Vehicle.js";
import VehicleFeature from "../../models/VehicleFeature.js";
import VehicleRecord from "../../models/VehicleRecord.js";

const buildUsedCarPath = (doc = {}) => {
  const stage = doc?.workflow?.currentStage || "lead-intake";
  const map = {
    "lead-intake": "/used-cars",
    inspection: "/used-cars/inspection",
    "background-check": "/used-cars/background-check",
    negotiation: "/used-cars/negotiation",
    documentation: "/used-cars/documentation",
    stock: "/used-cars/stock",
    procurement: "/used-cars/stock",
    closed: "/used-cars",
  };
  return `${map[stage] || "/used-cars"}?leadId=${doc?._id}`;
};

/**
 * Adapter contract:
 * - key: unique entity key
 * - model: mongoose model
 * - limit: per-entity limit
 * - projection: lean projection
 * - intents: query intent groups that should boost this adapter
 * - fields: paths grouped by matching semantics
 * - result(doc): normalized result card for frontend
 *
 * Add future entities here without changing global-search core logic.
 */
export const SEARCH_ADAPTERS = [
  {
    key: "insurance_case",
    label: "Insurance",
    model: InsuranceCase,
    limit: 8,
    intents: ["insurance", "payment", "latest", "document"],
    projection: {
      caseId: 1,
      customerName: 1,
      companyName: 1,
      mobile: 1,
      email: 1,
      registrationNumber: 1,
      vehicleMake: 1,
      vehicleModel: 1,
      vehicleVariant: 1,
      newPolicyNumber: 1,
      previousPolicyNumber: 1,
      sourceName: 1,
      source: 1,
      status: 1,
      currentStep: 1,
      usedCarFlowType: 1,
      policyJourneyClassification: 1,
      updatedAt: 1,
      createdAt: 1,
      newOdExpiryDate: 1,
      newTpExpiryDate: 1,
    },
    fields: {
      id: ["caseId", "newPolicyNumber", "previousPolicyNumber"],
      name: ["customerName", "companyName"],
      phone: ["mobile"],
      email: ["email"],
      registration: ["registrationNumber"],
      vehicle: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      reference: ["sourceName"],
      status: ["status", "usedCarFlowType", "policyJourneyClassification"],
      text: ["source", "usedCarFlowType", "policyJourneyClassification"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.caseId || String(doc._id),
      title: doc.companyName || doc.customerName || "Insurance Case",
      subtitle: [
        [doc.vehicleMake, doc.vehicleModel, doc.vehicleVariant].filter(Boolean).join(" "),
        doc.registrationNumber,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc.status || "draft",
      badge: doc.usedCarFlowType || "Insurance",
      route: doc.caseId ? `/insurance/edit/${encodeURIComponent(doc.caseId)}` : "/insurance",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "loan",
    label: "Loan",
    model: Loan,
    limit: 8,
    intents: ["loan", "payment", "latest", "document"],
    projection: {
      loanId: 1,
      customerName: 1,
      primaryMobile: 1,
      customerMobile: 1,
      email: 1,
      registrationNumber: 1,
      vehicleMake: 1,
      vehicleModel: 1,
      vehicleVariant: 1,
      sourceName: 1,
      dealerName: 1,
      status: 1,
      currentStage: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["loanId"],
      name: ["customerName"],
      phone: ["primaryMobile", "customerMobile"],
      email: ["email"],
      registration: ["registrationNumber"],
      vehicle: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      reference: ["sourceName", "dealerName"],
      status: ["status", "currentStage"],
      text: ["sourceName", "dealerName", "status", "currentStage"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.loanId || String(doc._id),
      title: doc.customerName || "Loan Case",
      subtitle: [
        [doc.vehicleMake, doc.vehicleModel, doc.vehicleVariant].filter(Boolean).join(" "),
        doc.registrationNumber,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc.status || "Pending",
      badge: doc.currentStage || "Loan",
      route: doc._id ? `/loans/edit/${doc._id}` : "/loans",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "used_car_lead",
    label: "Used Cars",
    model: UsedCarLead,
    limit: 10,
    intents: ["vehicle", "inspection", "challan", "payment", "rc", "latest"],
    projection: {
      internalLeadId: 1,
      seller: 1,
      vehicle: 1,
      source: 1,
      workflow: 1,
      scheduling: 1,
      backgroundCheck: 1,
      updatedAt: 1,
      createdAt: 1,
      leadDate: 1,
    },
    fields: {
      id: ["internalLeadId"],
      name: ["seller.name"],
      phone: ["seller.mobile", "seller.alternateMobile"],
      email: ["seller.email"],
      registration: ["vehicle.regNo"],
      vehicle: ["vehicle.make", "vehicle.model", "vehicle.variant", "vehicle.color"],
      reference: ["source", "seller.area", "seller.city"],
      status: ["workflow.status", "workflow.currentStage"],
      text: [
        "workflow.status",
        "workflow.currentStage",
        "workflow.closureReason",
        "backgroundCheck.formValues.roadTaxStatus",
        "backgroundCheck.formValues.rtoNocIssued",
      ],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.internalLeadId || String(doc._id),
      title: doc?.seller?.name || "Used Car Lead",
      subtitle: [
        [doc?.vehicle?.make, doc?.vehicle?.model, doc?.vehicle?.variant].filter(Boolean).join(" "),
        doc?.vehicle?.regNo,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc?.workflow?.status || "New",
      badge: doc?.workflow?.currentStage || "lead-intake",
      route: buildUsedCarPath(doc),
      updatedAt: doc.updatedAt || doc.leadDate || doc.createdAt,
    }),
  },
  {
    key: "customer",
    label: "Customers",
    model: Customer,
    limit: 8,
    intents: ["document", "latest"],
    projection: {
      customerId: 1,
      customerName: 1,
      primaryMobile: 1,
      email: 1,
      city: 1,
      panNumber: 1,
      aadhaarNumber: 1,
      gstNumber: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["customerId", "panNumber", "aadhaarNumber", "gstNumber"],
      name: ["customerName"],
      phone: ["primaryMobile"],
      email: ["email"],
      registration: [],
      vehicle: [],
      reference: ["city"],
      status: ["kycStatus"],
      text: ["city"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.customerId || String(doc._id),
      title: doc.customerName || "Customer",
      subtitle: [doc.primaryMobile, doc.city].filter(Boolean).join(" • "),
      status: doc.kycStatus || "Active",
      badge: "Customer",
      route: doc._id ? `/customers/edit/${doc._id}` : "/customers",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "vehicle_record",
    label: "Vehicle Master",
    model: VehicleRecord,
    limit: 8,
    intents: ["vehicle", "rc", "challan", "latest"],
    projection: {
      loanId: 1,
      customerName: 1,
      primaryMobile: 1,
      registrationNumber: 1,
      registrationNumberNormalized: 1,
      registrationNumberLast4: 1,
      make: 1,
      model: 1,
      variant: 1,
      fuelType: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["loanId"],
      name: ["customerName"],
      phone: ["primaryMobile"],
      email: [],
      registration: [
        "registrationNumber",
        "registrationNumberNormalized",
        "registrationNumberLast4",
      ],
      vehicle: ["make", "model", "variant", "fuelType"],
      reference: ["loanId"],
      status: [],
      text: ["make", "model", "variant", "fuelType"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.registrationNumber || doc.loanId || String(doc._id),
      title: [doc.make, doc.model, doc.variant].filter(Boolean).join(" ") || "Vehicle Record",
      subtitle: [doc.registrationNumber, doc.customerName].filter(Boolean).join(" • "),
      status: "Mapped",
      badge: "Vehicle",
      route: doc.loanId ? `/loans/edit/${encodeURIComponent(String(doc.loanId))}` : "/vehicles/price-list",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "vehicle_catalog",
    label: "Vehicle Catalog",
    model: Vehicle,
    limit: 8,
    intents: ["vehicle", "latest"],
    projection: {
      make: 1,
      model: 1,
      variant: 1,
      fuel: 1,
      fuel_type: 1,
      city: 1,
      status: 1,
      is_discontinued: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: [],
      name: [],
      phone: [],
      email: [],
      registration: [],
      vehicle: ["make", "model", "variant", "fuel", "fuel_type", "city"],
      reference: ["city"],
      status: ["status"],
      text: ["make", "model", "variant", "fuel", "fuel_type", "city"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: [doc.make, doc.model, doc.variant].filter(Boolean).join("-"),
      title: [doc.make, doc.model, doc.variant].filter(Boolean).join(" ") || "Vehicle Catalog",
      subtitle: [doc.city, doc.fuel_type || doc.fuel].filter(Boolean).join(" • "),
      status: doc.is_discontinued ? "Discontinued" : doc.status || "Active",
      badge: "Catalog",
      route: `/vehicles/price-list?search=${encodeURIComponent(
        [doc.make, doc.model, doc.variant].filter(Boolean).join(" "),
      )}`,
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "receivable",
    label: "Receivables",
    model: Receivable,
    limit: 8,
    intents: ["payment", "loan", "insurance", "latest"],
    projection: {
      loanId: 1,
      insuranceCaseId: 1,
      customerName: 1,
      payoutId: 1,
      payout_party_name: 1,
      payout_status: 1,
      payout_type: 1,
      payout_amount: 1,
      net_payout_amount: 1,
      sourceModule: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["loanId", "insuranceCaseId", "payoutId"],
      name: ["customerName", "payout_party_name"],
      phone: [],
      email: [],
      registration: [],
      vehicle: [],
      reference: ["sourceModule", "payout_type", "payout_status"],
      status: ["payout_status"],
      text: ["sourceModule", "payout_type", "payout_status", "receivableKind"],
      dateField: "updatedAt",
    },
    result: (doc) => {
      const route =
        doc.insuranceCaseId
          ? `/insurance/edit/${encodeURIComponent(String(doc.insuranceCaseId))}`
          : doc.loanId
            ? `/payouts/receivables?loanId=${encodeURIComponent(String(doc.loanId))}`
            : "/payouts/receivables";
      return {
        recordId: doc.payoutId || doc.insuranceCaseId || doc.loanId || String(doc._id),
        title: doc.customerName || doc.payout_party_name || "Receivable Entry",
        subtitle: [doc.sourceModule, doc.payout_type, doc.payout_status]
          .filter(Boolean)
          .join(" • "),
        status: doc.payout_status || "Pending",
        badge:
          Number(doc.net_payout_amount || doc.payout_amount || 0) > 0
            ? `₹${Number(doc.net_payout_amount || doc.payout_amount || 0).toLocaleString("en-IN")}`
            : "Receivable",
        route,
        updatedAt: doc.updatedAt || doc.createdAt,
      };
    },
  },
  {
    key: "quotation",
    label: "Quotations",
    model: Quotation,
    limit: 8,
    intents: ["vehicle", "loan", "latest", "payment"],
    projection: {
      _id: 1,
      customer: 1,
      vehicle: 1,
      pricing: 1,
      status: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: [],
      name: ["customer.customerName"],
      phone: ["customer.primaryMobile"],
      email: ["customer.email"],
      registration: [],
      vehicle: ["vehicle.make", "vehicle.model", "vehicle.variant", "pricing.color"],
      reference: ["customer.city", "cityTyped", "vehicleCity"],
      status: ["status"],
      text: ["status", "pricing.color", "customer.city", "vehicleCity", "cityTyped"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: String(doc._id),
      title: doc?.customer?.customerName || "Quotation",
      subtitle: [
        [doc?.vehicle?.make, doc?.vehicle?.model, doc?.vehicle?.variant].filter(Boolean).join(" "),
        doc?.pricing?.color,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc.status || "draft",
      badge: Number(doc?.pricing?.netOnRoad || 0) > 0
        ? `₹${Number(doc?.pricing?.netOnRoad || 0).toLocaleString("en-IN")}`
        : "Quote",
      route: `/loans/quotations?focus=${encodeURIComponent(String(doc._id))}`,
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "payment_sheet",
    label: "Payments",
    model: Payment,
    limit: 6,
    intents: ["payment", "loan", "latest"],
    projection: {
      loanId: 1,
      customerName: 1,
      primaryMobile: 1,
      vehicleMake: 1,
      vehicleModel: 1,
      vehicleVariant: 1,
      do_refNo: 1,
      doNumber: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["loanId", "do_refNo", "doNumber"],
      name: ["customerName"],
      phone: ["primaryMobile"],
      email: [],
      registration: [],
      vehicle: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      reference: ["loanId", "do_refNo", "doNumber"],
      status: [],
      text: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.loanId || String(doc._id),
      title: doc.customerName || `Payment ${doc.loanId || ""}`,
      subtitle: [
        [doc.vehicleMake, doc.vehicleModel, doc.vehicleVariant].filter(Boolean).join(" "),
        doc.do_refNo || doc.doNumber,
      ]
        .filter(Boolean)
        .join(" • "),
      status: "Payments",
      badge: "Ledger",
      route: doc.loanId ? `/payments/${encodeURIComponent(String(doc.loanId))}` : "/payments",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "delivery_order",
    label: "Delivery Orders",
    model: DeliveryOrder,
    limit: 6,
    intents: ["loan", "payment", "document", "latest"],
    projection: {
      loanId: 1,
      do_loanId: 1,
      customerName: 1,
      do_customerName: 1,
      primaryMobile: 1,
      vehicleMake: 1,
      vehicleModel: 1,
      vehicleVariant: 1,
      doNumber: 1,
      do_refNo: 1,
      status: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["loanId", "do_loanId", "doNumber", "do_refNo"],
      name: ["customerName", "do_customerName"],
      phone: ["primaryMobile"],
      email: [],
      registration: [],
      vehicle: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      reference: ["do_refNo", "doNumber"],
      status: ["status"],
      text: ["status", "vehicleMake", "vehicleModel"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.do_refNo || doc.doNumber || doc.loanId || String(doc._id),
      title: doc.do_customerName || doc.customerName || "Delivery Order",
      subtitle: [
        [doc.vehicleMake, doc.vehicleModel, doc.vehicleVariant].filter(Boolean).join(" "),
        doc.do_refNo || doc.doNumber,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc.status || "Generated",
      badge: "DO",
      route: `/delivery-orders/${encodeURIComponent(String(doc.do_loanId || doc.loanId || ""))}`,
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "booking",
    label: "Bookings",
    model: Booking,
    limit: 6,
    intents: ["vehicle", "payment", "latest", "document"],
    projection: {
      bookingId: 1,
      customerName: 1,
      customerPhone: 1,
      vehicleMake: 1,
      vehicleModel: 1,
      vehicleVariant: 1,
      dealerName: 1,
      directSourceName: 1,
      status: 1,
      linkedLoanId: 1,
      bookingAmount: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["bookingId", "linkedLoanId"],
      name: ["customerName"],
      phone: ["customerPhone"],
      email: [],
      registration: [],
      vehicle: ["vehicleMake", "vehicleModel", "vehicleVariant"],
      reference: ["dealerName", "directSourceName"],
      status: ["status"],
      text: ["status", "dealerName", "directSourceName"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.bookingId || String(doc._id),
      title: doc.customerName || "Booking",
      subtitle: [
        [doc.vehicleMake, doc.vehicleModel, doc.vehicleVariant].filter(Boolean).join(" "),
        doc.dealerName || doc.directSourceName,
      ]
        .filter(Boolean)
        .join(" • "),
      status: doc.status || "Open",
      badge: doc.bookingAmount ? `₹${Number(doc.bookingAmount).toLocaleString("en-IN")}` : "Booking",
      route: doc.bookingId ? `/bookings/${encodeURIComponent(String(doc.bookingId))}` : "/bookings",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "showroom",
    label: "Showrooms",
    model: Showroom,
    limit: 6,
    intents: ["document", "payment", "latest"],
    projection: {
      showroomId: 1,
      name: 1,
      businessName: 1,
      contactPerson: 1,
      mobile: 1,
      email: 1,
      city: 1,
      state: 1,
      status: 1,
      brands: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["showroomId"],
      name: ["name", "businessName", "contactPerson"],
      phone: ["mobile", "alternatePhone"],
      email: ["email"],
      registration: [],
      vehicle: ["brands"],
      reference: ["city", "state"],
      status: ["status"],
      text: ["name", "businessName", "contactPerson", "city", "state", "status"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.showroomId || String(doc._id),
      title: doc.businessName || doc.name || "Showroom",
      subtitle: [doc.contactPerson, doc.mobile, doc.city].filter(Boolean).join(" • "),
      status: doc.status || "Active",
      badge: "Showroom",
      route: doc._id
        ? `/superadmin/showrooms/${encodeURIComponent(String(doc._id))}`
        : "/superadmin/showrooms",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "channel",
    label: "Channels",
    model: Channel,
    limit: 6,
    intents: ["payment", "latest"],
    projection: {
      channelId: 1,
      name: 1,
      businessName: 1,
      contactPerson: 1,
      mobile: 1,
      email: 1,
      city: 1,
      type: 1,
      status: 1,
      dsaCode: 1,
      dealerCode: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["channelId", "dsaCode", "dealerCode"],
      name: ["name", "businessName", "contactPerson"],
      phone: ["mobile", "alternatePhone"],
      email: ["email"],
      registration: [],
      vehicle: [],
      reference: ["city", "type"],
      status: ["status"],
      text: ["name", "businessName", "contactPerson", "city", "type", "status"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.channelId || String(doc._id),
      title: doc.businessName || doc.name || "Channel",
      subtitle: [doc.contactPerson, doc.mobile, doc.city].filter(Boolean).join(" • "),
      status: doc.status || "Active",
      badge: doc.type || "Channel",
      route: "/superadmin/channels",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "bank",
    label: "Banks",
    model: Bank,
    limit: 6,
    intents: ["payment", "loan", "latest"],
    projection: {
      name: 1,
      ifsc: 1,
      address: 1,
      createdAt: 1,
      updatedAt: 1,
    },
    fields: {
      id: ["ifsc"],
      name: ["name"],
      phone: [],
      email: [],
      registration: [],
      vehicle: [],
      reference: ["ifsc", "address"],
      status: [],
      text: ["name", "ifsc", "address"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.ifsc || String(doc._id),
      title: doc.name || "Bank",
      subtitle: [doc.ifsc, doc.address].filter(Boolean).join(" • "),
      status: "Bank Directory",
      badge: "Bank",
      route: doc._id
        ? `/superadmin/banks/${encodeURIComponent(String(doc._id))}`
        : "/superadmin/banks",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "bank_directory",
    label: "Bank Directory",
    model: BankDirectory,
    limit: 6,
    intents: ["payment", "loan", "latest"],
    projection: {
      ifsc: 1,
      micr: 1,
      bankName: 1,
      branch: 1,
      address: 1,
      city: 1,
      state: 1,
      district: 1,
      active: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: ["ifsc", "micr"],
      name: ["bankName", "branch"],
      phone: [],
      email: [],
      registration: [],
      vehicle: [],
      reference: ["city", "state", "district", "address"],
      status: ["active"],
      text: ["bankName", "branch", "ifsc", "micr", "city", "state", "district"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: doc.ifsc || String(doc._id),
      title: doc.bankName || "Bank Directory",
      subtitle: [doc.branch, doc.city, doc.state].filter(Boolean).join(" • "),
      status: doc.active === false ? "Inactive" : "Active",
      badge: "IFSC",
      route: "/superadmin/banks",
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
  {
    key: "vehicle_feature",
    label: "Vehicle Features",
    model: VehicleFeature,
    limit: 6,
    intents: ["vehicle", "latest"],
    projection: {
      brand: 1,
      model: 1,
      variant: 1,
      body_type_bucket: 1,
      seating_capacity: 1,
      updatedAt: 1,
      createdAt: 1,
    },
    fields: {
      id: [],
      name: [],
      phone: [],
      email: [],
      registration: [],
      vehicle: ["brand", "model", "variant", "body_type_bucket"],
      reference: ["brand", "model", "variant"],
      status: [],
      text: ["brand", "model", "variant", "body_type_bucket"],
      dateField: "updatedAt",
    },
    result: (doc) => ({
      recordId: [doc.brand, doc.model, doc.variant].filter(Boolean).join("-"),
      title: [doc.brand, doc.model, doc.variant].filter(Boolean).join(" ") || "Vehicle Feature",
      subtitle: [
        doc.body_type_bucket,
        Number.isFinite(doc.seating_capacity)
          ? `${doc.seating_capacity} seats`
          : "",
      ]
        .filter(Boolean)
        .join(" • "),
      status: "Feature Catalog",
      badge: "Specs",
      route: `/loans/features?search=${encodeURIComponent(
        [doc.brand, doc.model, doc.variant].filter(Boolean).join(" "),
      )}`,
      updatedAt: doc.updatedAt || doc.createdAt,
    }),
  },
];
